service:
  name: serverless-api

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws

functions:
  hello:
    handler: src/contexts/users/infra/handlers/testeHandlers.handle
    events:
      - http:
          path: /teste
          method: GET
          cors: true